fix: Some fixes for swaps
InjectiveLabs/injective-dex pull request #831
Opened 2022-05-30 16:12 UTC by afterburn

This PR should resolve the following issues brought to my attention by @Tofel.

1. Ask user to connect wallet on mount.
3. Revert to old TokenSelector for Transfer modal.
4. Missing tooltip for slippage tolerance in AdvancedSettings.
5. Limit/clamp max slippage tolerance.
8. Bug: Able to execute swap even though user doesn't have a valid market.
14. Bug: If user doesnt have sufficient balance we show Injective Hub link instead of Go to Portfolio link.
16. Bug: In case of "not a valid number" error we're currently seeing a Go to Portfolio link, this should not be the case.
25. Bug: Maxing TokenSelector will not hide the max button if the amount of decimal places do not match.
27. When searching the assets layout doesn't match Figma. 1/2
28. Bug: Balances don’t show up correctly when there is no valid market.
29. Flip default market for swaps to USDT → INJ instead of USDT → INJ.

2022-05-30 16:27 UTC, bangjelkoski commented
Nice one!

2022-05-30 16:27 UTC, bangjelkoski requested changes

2022-05-30 16:27 UTC, bangjelkoski commented on components/inputs/input.vue
> +      if (max !== null && Number(value) > Number(max)) {
Blank row above please, same for the 409 line

2022-06-01 09:34 UTC, ThomasRalee commented on components/partials/swap/index.vue
> +        slippageToleranceAsNumber <= maxSlippage.toNumber()
Let's do a bigNumberInBase comparison instead
```
const slippageToleranceInBigNumber = new BigNumberInBase(form.slippageTolerance)

const slippageToTolerance = maxSlippage.gte(slippageToleranceInBigNumber) ? slippageToleranceInBigNumber : maxSlippage
```

2022-06-01 09:34 UTC, ThomasRalee commented on components/partials/swap/index.vue
> +      const slippageTolerance = Number(this.form.slippageTolerance)
Lets use BigNumberInBase instead of Number here

2022-06-01 10:33 UTC, Tofel commented
`15`. fixed ✅ 
`31`. fixed ✅ 
`32`.  waiting for @terencetang9 input whether we should block all inputs and selector or just the SWAP button ❓
`33`. almost ✅  / ❌  it works as expected if the query params are missing, but it doesn't if they have invalid value (e.g.`from=dhdhsdsd&to=usdt`)
`35`. fixed ✅ 
`36`. fixed ✅

2022-06-01 12:46 UTC, Tofel commented
33. fixed ✅

2022-06-01 15:03 UTC, bangjelkoski commented
Are there other things that are pending to be fixed? @afterburn @Tofel

2022-06-02 10:17 UTC, merged