[WIP] refactor: spot trade order form
InjectiveLabs/injective-dex pull request #886
Opened 2022-06-21 13:22 UTC by shane-moore

2022-06-22 13:04 UTC, afterburn commented on components/partials/common/trade/advanced-settings/error.vue
> +        new BigNumberInBase(slippageTolerance).gt(new BigNumberInBase(5)) &&
Perhaps here you can put `new BigNumberInBase(slippageTolerance)` in a variable and reuse that as opposed to creating new BigNumbersInBase multiple times, more readable and less garbage collection

2022-06-22 14:41 UTC, bangjelkoski requested changes

2022-06-22 14:41 UTC, bangjelkoski commented on components/partials/common/trade/advanced-settings/index.vue
>        this.$emit('set-reduce-only', checked)
Let's follow the pattern of `action:item` for the event names, here lets say we can have `update:reduceOnly` and above we have have `set:advancedSettingsErrors`

2022-06-22 14:52 UTC, ThomasRalee commented on components/partials/common/trade/advanced-settings/error.vue
> +    slippageError(): string | undefined {
Lets use `slippageTooHighError` directly and remove `slippageError` and `hasError` computed property

2022-06-22 15:14 UTC, ThomasRalee commented on components/partials/common/trade/order-inputs.vue
> +    priceStep(): string {
Let's abstract `amountStep` to this component and abstract the way we format the placeholder values from the decimalPlaces into a function on the `formatter.ts` file.

2022-06-22 15:14 UTC, ThomasRalee commented on components/partials/common/trade/order-inputs.vue
> +
move the line break from 369 to 368

2022-06-24 17:32 UTC, ThomasRalee approved these changes

2022-06-25 14:31 UTC, merged