Fee Discounts page redesign
InjectiveLabs/injective-dex pull request #888
Opened 2022-06-22 13:57 UTC by afterburn

This PR closes [#59](https://app.zenhub.com/workspaces/product-engineering-team-6228558038ca2f002011c6a3/issues/injectivelabs/product-zenhub-workspace/59)

[FIGMA DESIGN FILE](https://www.figma.com/file/qJtXzfX9nzh0c7yA6G9iI3/Injective-DEX?node-id=5053%3A8645)

<img width="832" alt="image" src="https://user-images.githubusercontent.com/10757768/176306795-8ed991e2-b048-4ddd-8706-0c9d3437a58b.png">
<img width="288" alt="image" src="https://user-images.githubusercontent.com/10757768/176306873-ef6d7e5f-2d05-4c52-bab1-3ff2d5d43b96.png">

2022-06-27 12:37 UTC, afterburn commented
Ready for review, but don't merge until [this PR](https://github.com/InjectiveLabs/injective-ts/pull/42) has been merged.

2022-06-28 14:38 UTC, bangjelkoski requested changes

2022-06-28 14:38 UTC, bangjelkoski commented on components/partials/fee-discounts/overview.vue
> +          v-for="i in 3"
Way too hacky, let's do some other approach here `[...Array(3).keys()]` maybe or `Array.from(Array(3).keys())`

2022-06-28 14:38 UTC, bangjelkoski commented on components/partials/fee-discounts/overview.vue
> +          :class="slideIndex === i - 1 ? 'bg-opacity-50' : 'bg-opacity-10'"
okay, this is fine but in general when something like this needs to happen it's better to extract it to component that has a computed property, it's much cleaner

2022-06-28 14:38 UTC, bangjelkoski commented on components/partials/fee-discounts/overview.vue
> +      this.slideIndex = Math.round((offset / total) * 2)
The blank row above. The reason why is that they are different blocks, the first block is defining variables and the second one is setting a state variable.

2022-06-28 19:19 UTC, ThomasRalee commented on components/partials/fee-discounts/fees/tier.vue
>        ).toBase(6 /* USDT */)
Nitpick here, lets move 6 to the constant file for e.g. `USDT_DECIMAL_PLACE: number = 6` and use it here and remove the comment

2022-06-28 19:21 UTC, ThomasRalee commented on components/partials/fee-discounts/overview.vue
> +.fee-discounts-statistic {
Let's move this class to tailwind the `tailwind.config.js` file, for [example](https://v2.tailwindcss.com/docs/flex#flex-values).

2022-06-28 19:30 UTC, ThomasRalee commented on components/partials/fee-discounts/overview.vue
> +    lastUpdateTimestamp(): string {
Lets return `string | undefined` here and use `&mdash;` in HTML.

```
<span v-if="lastUpdateTimestamp">{{ lastUpdateTimestamp }}</span>
<span v-else>&mdash;</span>
```

2022-06-28 19:31 UTC, ThomasRalee commented on components/partials/fee-discounts/overview.vue
>      feeDiscountAccountInfo(): FeeDiscountAccountInfo | undefined {
Lets move store variables computed properties to the top, same with `feeDiscountSchedule`

2022-06-28 19:31 UTC, ThomasRalee commented on components/partials/fee-discounts/overview.vue
> +    aprToFormat(): string {
Let move this below store variables computed property

2022-06-28 19:34 UTC, ThomasRalee commented
Can we please upload screenshots and the Figma link for PR that involves design changes?

2022-06-28 21:57 UTC, afterburn commented
> Can we please upload screenshots and the Figma link for in the PR description, when the implementation involves design changes?

Hey @ThomasRalee I was a bit too quick to remove this PR from draft status as I still had some cleaned up code locally that I still had to push. There is a lot of new stuff/restructuring so please review again when you have the time. I also resolved your comments.

2022-06-28 22:19 UTC, ThomasRalee commented on components/elements/horizontal-scroll-view-indicator.vue
> +      required: true,
Let's remove `required` here

2022-06-28 22:19 UTC, ThomasRalee commented on components/elements/horizontal-scroll-view.vue
> +        v-for="i in viewCount"
Let's use `index` instead of `i`

2022-06-28 22:20 UTC, ThomasRalee commented on components/elements/horizontal-scroll-view.vue
> +    const viewsElement = this.$refs.views as HTMLElement
Let's add a line break here

2022-06-28 22:22 UTC, ThomasRalee commented on components/partials/fee-discounts/overview.vue
> +          <StakedAmount />
Let's move the class to the custom components, for example:
```
<StakedAmount class="flex-0-full md:col-span-3" />
```

2022-06-28 22:23 UTC, ThomasRalee commented on components/partials/fee-discounts/staked-amount.vue
> +      if (!feeDiscountAccountInfo) {
Let's combine the condition checks, for example:
```
if (!feeDiscountAccountInfo || !feeDiscountAccountInfo.accountInfo) {
    return ZERO_IN_BASE
}
```

2022-06-28 22:23 UTC, ThomasRalee commented on components/partials/fee-discounts/staked-amount.vue
> +    apr(): BigNumberInBase {
Let's move store variables computed property to the top

2022-06-29 08:09 UTC, bangjelkoski requested changes

2022-06-29 08:09 UTC, bangjelkoski commented on app/utils/constants.ts
> +export const USDT_DECIMAL_PLACE = 6
`USDT_DECIMALS` is a better name for this variable

2022-07-01 11:41 UTC, bangjelkoski commented
[PR](https://github.com/InjectiveLabs/injective-ts/pull/42) merged

2022-07-04 12:49 UTC, Tofel commented
LGTM ✅ 

Should we merge it?

2022-07-04 14:08 UTC, afterburn commented
I'm merging this, for future reference (if any0 I got verbal approval from @bangjelkoski [here](https://injectivelabsinc.slack.com/archives/C03FM3MHHRU/p1656943413681589?thread_ts=1656921977.429509&cid=C03FM3MHHRU).

2022-07-04 14:08 UTC, merged